language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

env:
  matrix:
    - DB=sqlite db_dsn='sqlite:///:memory:'
  global:
    - DEFAULT=1

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

  fast_finish: true

  include:
    - php: 7.0
      env: PHPCS=1 DEFAULT=0

    - php: hhvm
      env: HHVM=1 DB=sqlite db_dsn='sqlite:///:memory:'

    - php: hhvm-nightly
      env: HHVM=1 DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

  - phpenv rehash
  - set +H

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=config/Migrations/* ./src ./tests ./config; fi"

notifications:
  email: false
